# SA Audio Runtime v2.0.0
# Created by sonochiwa
# Source code: https://github.com/sonochiwa/sa-audio-runtime
# Default toggle hotkey: Alt + Y

[General]
isEnabled=1
hotkeyEnabled=1
hotkeyModifier=18
hotkeyKey=89
showNotifications=1

[WeaponAudio]
gunshots=1
bulletImpacts=1
effects=1

[VehicleAudio]
engines=1
effects=1
collisions=1

[CharacterAudio]
dialogues=1
scanner=1
effects=1

[WorldAudio]
explosions=1
ambience=1
miscEffects=1
