# Audio Runtime v2.3.0
# Created by sonochiwa
# Source code: https://github.com/sonochiwa/sa-audio-runtime
# Default toggle hotkey: Alt + Y

[general]
isEnabled=1
hotkeyEnabled=1
hotkeyModifier=18
hotkeyKey=89
